# Slide 22: Set up configuration for Alertmanager (Step 6)
route:
  # Basic configuration: all alerts will go through emailer
  receiver: emailer
receivers:
  - name: emailer
    # Include details for sending email alert through Gmail
    email_configs:
      - to: leewengyancynthia@gmail.com
        from: leewengyancynthia@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: leewengyancynthia@gmail.com
        auth_identity: leewengyancynthia@gmail.com
        auth_password: ccfytjsmgsfskylt
