global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "slotify"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["slotify:3001"]

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093

rule_files:
  - "rules.yml"
